# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ipam.fields


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0002_auto_20170222_1210'),
        ('ipam', '0015_global_vlans'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='virtual_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='virtual.VirtualInterface'),
        )
    ]
