# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:34
from __future__ import unicode_literals

import dcim.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0006_auto_20170222_1434'),
        ('dcim', '0029_allow_rackless_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='virtual_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='virtual.VirtualCluster'),
        ),
    ]
