# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0002_auto_20170222_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='primary_ip4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ip4_for_virtual', to='ipam.IPAddress', verbose_name='Primary IPv4'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='primary_ip6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_ip6_for_virtual', to='ipam.IPAddress', verbose_name='Primary IPv6'),
        ),
    ]
