# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0004_virtualmachinegroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='status',
            field=models.BooleanField(choices=[[True, 'Active'], [False, 'Offline']], default=True, verbose_name='Status'),
        ),
    ]
